version: "3.9"
services:
  mysql:
    image: "mysql:8"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=vjudb"
    ports:
      - "33306:3306"
